In [17]:
import pandas as pd

In [18]:
results = pd.read_csv(
    "../artifacts/metrics/experiment_results.csv"
)

results

,timestamp,model,sampling,precision,recall,f1_score,roc_auc,pr_auc,threshold,train_samples,fraud_samples,training_time_sec
0,2026-05-20T00:03:04.292692,logistic_regression,none,0.027347,0.918367,0.053113,0.972083,0.718971,0.3,227845,394,0.3956
1,2026-05-20T00:03:17.535909,random_forest,none,0.922222,0.846939,0.882979,0.952909,0.855418,0.3,227845,394,13.0469
2,2026-05-20T00:03:18.306027,xgboost,none,0.908046,0.806122,0.854054,0.977071,0.861214,0.3,227845,394,0.5830
3,2026-05-20T00:03:18.498284,logistic_regression,undersampling,0.024443,0.918367,0.047619,0.975192,0.457838,0.3,788,394,0.0025
4,2026-05-20T00:03:18.767180,random_forest,undersampling,0.014536,0.948980,0.028633,0.977782,0.695626,0.3,788,394,0.0783
5,2026-05-20T00:03:19.048313,xgboost,undersampling,0.026346,0.928571,0.051239,0.978660,0.611876,0.3,788,394,0.1054
6,2026-05-20T00:03:20.917943,logistic_regression,oversampling,0.027422,0.918367,0.053254,0.971952,0.711174,0.3,454902,227451,1.5863
7,2026-05-20T00:03:39.027912,random_forest,oversampling,0.881720,0.836735,0.858639,0.962818,0.856072,0.3,454902,227451,17.9116
8,2026-05-20T00:03:40.214784,xgboost,oversampling,0.639706,0.887755,0.743590,0.975788,0.869042,0.3,454902,227451,0.9906
9,2026-05-20T00:03:41.897889,logistic_regression,smote,0.072299,0.908163,0.133935,0.976482,0.734231,0.3,454902,227451,1.2895
10,2026-05-20T00:04:26.845601,random_forest,smote,0.679688,0.887755,0.769912,0.964422,0.874608,0.3,454902,227451,44.7357
11,2026-05-20T00:04:28.142475,xgboost,smote,0.354839,0.897959,0.508671,0.979487,0.861906,0.3,454902,227451,1.0595

In [20]:
results.sort_values(
    by="pr_auc",
    ascending=False
)

,timestamp,model,sampling,precision,recall,f1_score,roc_auc,pr_auc,threshold,train_samples,fraud_samples,training_time_sec
10,2026-05-20T00:04:26.845601,random_forest,smote,0.679688,0.887755,0.769912,0.964422,0.874608,0.3,454902,227451,44.7357
8,2026-05-20T00:03:40.214784,xgboost,oversampling,0.639706,0.887755,0.743590,0.975788,0.869042,0.3,454902,227451,0.9906
11,2026-05-20T00:04:28.142475,xgboost,smote,0.354839,0.897959,0.508671,0.979487,0.861906,0.3,454902,227451,1.0595
2,2026-05-20T00:03:18.306027,xgboost,none,0.908046,0.806122,0.854054,0.977071,0.861214,0.3,227845,394,0.5830
7,2026-05-20T00:03:39.027912,random_forest,oversampling,0.881720,0.836735,0.858639,0.962818,0.856072,0.3,454902,227451,17.9116
1,2026-05-20T00:03:17.535909,random_forest,none,0.922222,0.846939,0.882979,0.952909,0.855418,0.3,227845,394,13.0469
9,2026-05-20T00:03:41.897889,logistic_regression,smote,0.072299,0.908163,0.133935,0.976482,0.734231,0.3,454902,227451,1.2895
0,2026-05-20T00:03:04.292692,logistic_regression,none,0.027347,0.918367,0.053113,0.972083,0.718971,0.3,227845,394,0.3956
6,2026-05-20T00:03:20.917943,logistic_regression,oversampling,0.027422,0.918367,0.053254,0.971952,0.711174,0.3,454902,227451,1.5863
4,2026-05-20T00:03:18.767180,random_forest,undersampling,0.014536,0.948980,0.028633,0.977782,0.695626,0.3,788,394,0.0783
5,2026-05-20T00:03:19.048313,xgboost,undersampling,0.026346,0.928571,0.051239,0.978660,0.611876,0.3,788,394,0.1054
3,2026-05-20T00:03:18.498284,logistic_regression,undersampling,0.024443,0.918367,0.047619,0.975192,0.457838,0.3,788,394,0.0025